Write a python program to import and export data using Pandas and
show the details of the dataset like number of rows, columns, first five
rows, size, number of missing values, sum, average, min and max
values from the numerical columns.

In [3]:
import pandas as pd

In [16]:
import numpy as np

In [4]:
from google.colab import files

In [5]:
uploaded = files.upload()

Saving student-dataset.csv to student-dataset.csv

In [6]:
import io

In [7]:
df = pd.read_csv(io.BytesIO(uploaded['student-dataset.csv']))

In [8]:
df.head(5)

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

In [9]:
df.shape

(307, 16)

In [10]:
df.tail(10)

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
297,297,Cody Smith,United States of America,Charlotte,35.23,-80.84,M,NaN,23,3.8,3.5,3.9,5.0,5,2.0,5
298,298,Nicolas Papp,United States of America,New York,40.71,-74.01,M,NaN,23,2.7,3.7,3.9,5.0,5,4.0,4
299,299,Christopher Inhulsen,United States of America,Fort Worth,32.73,-97.32,M,NaN,23,3.1,3.3,2.9,5.0,2,4.0,4
300,300,Tessa Rawanduzy,United States of America,Derby,37.55,-97.27,F,NaN,21,3.3,3.3,2.0,5.0,3,3.0,5
301,301,Vanessa Gonzalez,Nicaragua,León,12.44,-86.88,F,NaN,24,3.3,3.7,3.8,3.0,5,5.0,4
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5

In [11]:
df.isna().sum()

id                      0
name                    0
nationality             0
city                    0
latitude                0
longitude               0
gender                  0
ethnic.group          307
age                     0
english.grade           0
math.grade              0
sciences.grade          0
language.grade          0
portfolio.rating        0
coverletter.rating      0
refletter.rating        0
dtype: int64

In [12]:
df.describe()

,id,latitude,longitude,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
count,307.000000,307.000000,307.000000,0.0,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,153.000000,32.863388,-64.539121,NaN,21.964169,3.369707,3.414332,3.446580,4.396417,3.986971,4.110749,4.188925
std,88.767487,13.498582,81.249146,NaN,1.248013,0.538724,0.476839,0.509081,0.996474,0.928749,0.823936,0.842193
min,0.000000,-33.450000,-123.130000,NaN,19.000000,1.500000,2.100000,1.400000,1.000000,1.000000,1.000000,1.000000
25%,76.500000,32.720000,-118.240000,NaN,21.000000,3.100000,3.100000,3.200000,4.000000,3.500000,4.000000,4.000000
50%,153.000000,34.390000,-99.140000,NaN,22.000000,3.500000,3.500000,3.600000,5.000000,4.000000,4.000000,4.000000
75%,229.500000,38.960000,-73.855000,NaN,23.000000,3.800000,3.800000,3.800000,5.000000,5.000000,5.000000,5.000000
max,306.000000,59.890000,139.750000,NaN,26.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000

In [13]:
print(f"\nDataset size: {df.memory_usage().sum() / 1024:.2f} KB")

Dataset size: 38.50 KB

In [17]:
numeric_columns = df.select_dtypes(include=[np.number]).columns
print("\nSummary statistics for numeric columns:")
print(df[numeric_columns].describe())

Summary statistics for numeric columns:
               id    latitude   longitude  ethnic.group         age  \
count  307.000000  307.000000  307.000000           0.0  307.000000
mean   153.000000   32.863388  -64.539121           NaN   21.964169
std     88.767487   13.498582   81.249146           NaN    1.248013
min      0.000000  -33.450000 -123.130000           NaN   19.000000
25%     76.500000   32.720000 -118.240000           NaN   21.000000
50%    153.000000   34.390000  -99.140000           NaN   22.000000
75%    229.500000   38.960000  -73.855000           NaN   23.000000
max    306.000000   59.890000  139.750000           NaN   26.000000

       english.grade  math.grade  sciences.grade  language.grade  \
count     307.000000  307.000000      307.000000      307.000000
mean        3.369707    3.414332        3.446580        4.396417
std         0.538724    0.476839        0.509081        0.996474
min         1.500000    2.100000        1.400000        1.000000
25%         3.100000    3.100000        3.200000        4.000000
50%         3.500000    3.500000        3.600000        5.000000
75%         3.800000    3.800000        3.800000        5.000000
max         4.000000    4.000000        4.000000        5.000000

       portfolio.rating  coverletter.rating  refletter.rating
count        307.000000          307.000000        307.000000
mean           3.986971            4.110749          4.188925
std            0.928749            0.823936          0.842193
min            1.000000            1.000000          1.000000
25%            3.500000            4.000000          4.000000
50%            4.000000            4.000000          4.000000
75%            5.000000            5.000000          5.000000
max            5.000000            5.000000          5.000000

In [18]:
# Import data
# For this example, we'll create a sample dataset
data = {
    'Name': ['Ali', 'Bhanu', 'Chanu', 'Dawood', 'Eric'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 60000, 75000, 90000, 100000],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
    'Experience': [2, 5, 8, 12, 15]
}

In [19]:
df = pd.DataFrame(data)

In [20]:
output_file = 'student-dataset.csv'
df.to_csv(output_file, index=False)
print(f"\nData exported to {output_file}")

Data exported to student-dataset.csv

In [21]:
imported_df = pd.read_csv(output_file)